# Codecov configuration for freethreading project
# https://docs.codecov.com/docs/codecov-yaml

coverage:
  status:
    project:
      default:
        target: 95

    patch:
      default:
        target: 95
        threshold: 5

  ignore:
    - "tests/**"
    - "docs/**"
    - "**/__pycache__/**"
